// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               unknown
// source: core/core.proto

/* eslint-disable */

export interface CheckRes {
  success: boolean;
}

export interface IDReq {
  id: number;
}
