// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               unknown
// source: admin/v1/i_menu.proto

/* eslint-disable */
import {
  type CreateMenuRequest,
  type DeleteMenuRequest,
  type ListMenuRequest,
  type ListMenuResponse,
  type Menu,
  type UpdateMenuRequest,
} from "../../entpb/entpb.pb";
import { type Empty } from "../../google/protobuf/empty.pb";

/** 后台菜单服务 */
export interface MenuService {
  /** 查询菜单列表 */
  List(request: ListMenuRequest): Promise<ListMenuResponse>;
  Create(request: CreateMenuRequest): Promise<Menu>;
  Update(request: UpdateMenuRequest): Promise<Menu>;
  Delete(request: DeleteMenuRequest): Promise<Empty>;
}
