// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               unknown
// source: admin/v1/i_organization.proto

/* eslint-disable */
import {
  type CreateDepartmentRequest,
  type DeleteDepartmentRequest,
  type Department,
  type GetDepartmentRequest,
  type ListDepartmentRequest,
  type ListDepartmentResponse,
  type UpdateDepartmentRequest,
} from "../../entpb/entpb.pb";
import { type Empty } from "../../google/protobuf/empty.pb";

/** 组织部门管理服务 */
export interface OrganizationService {
  Create(request: CreateDepartmentRequest): Promise<Department>;
  Get(request: GetDepartmentRequest): Promise<Department>;
  Update(request: UpdateDepartmentRequest): Promise<Department>;
  Delete(request: DeleteDepartmentRequest): Promise<Empty>;
  List(request: ListDepartmentRequest): Promise<ListDepartmentResponse>;
}
