// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               unknown
// source: admin/v1/i_router.proto

/* eslint-disable */
import { type Empty } from "../../google/protobuf/empty.pb";

export interface MenuInfo {
  id?: number | null | undefined;
  createdAt?: string | null | undefined;
  updatedAt?: string | null | undefined;
  level?: number | null | undefined;
  parentId?: number | null | undefined;
  path?: string | null | undefined;
  name?: string | null | undefined;
  redirect?: string | null | undefined;
  component?: string | null | undefined;
  sort?: number | null | undefined;
  disabled?: boolean | null | undefined;
  meta?: Meta | null | undefined;
  menuType?: number | null | undefined;
  serviceName?: string | null | undefined;
  permission?: string | null | undefined;
}

export interface MenuInfoList {
  total: string;
  data: MenuInfo[];
}

export interface MenuRoleInfo {
  id: string;
  menuId: string;
  roleId: string;
}

export interface MenuRoleListResp {
  total: string;
  data: MenuRoleInfo[];
}

export interface Meta {
  title?: string | null | undefined;
  icon?: string | null | undefined;
  hideMenu?: boolean | null | undefined;
  hideBreadcrumb?: boolean | null | undefined;
  ignoreKeepAlive?: boolean | null | undefined;
  hideTab?: boolean | null | undefined;
  frameSrc?: string | null | undefined;
  carryParam?: boolean | null | undefined;
  hideChildrenInMenu?: boolean | null | undefined;
  affix?: boolean | null | undefined;
  dynamicLevel?: number | null | undefined;
  realPath?: string | null | undefined;
}

/** 查询权限码列表 - 回应 */
export interface ListPermissionCodeResponse {
  codes: string[];
}

/** 网站后台动态路由服务 */
export interface RouterService {
  /** 查询路由列表 */
  ListRoute(request: Empty): Promise<MenuInfoList>;
  /** 查询权限码列表 */
  ListPermissionCode(request: Empty): Promise<ListPermissionCodeResponse>;
}
