// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               unknown
// source: admin/v1/i_street.proto

/* eslint-disable */
import { type ListStreetRequest, type ListStreetResponse } from "../../entpb/entpb.pb";

export interface StreetService {
  List(request: ListStreetRequest): Promise<ListStreetResponse>;
}
