// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               unknown
// source: admin/v1/i_sysapi.proto

/* eslint-disable */
import {
  type BatchCreateSysApisRequest,
  type BatchCreateSysApisResponse,
  type CreateSysApiRequest,
  type DeleteSysApiRequest,
  type GetSysApiRequest,
  type ListSysApiRequest,
  type ListSysApiResponse,
  type SysApi,
  type UpdateSysApiRequest,
} from "../../entpb/entpb.pb";
import { type Empty } from "../../google/protobuf/empty.pb";

export interface SysApiService {
  Create(request: CreateSysApiRequest): Promise<SysApi>;
  Get(request: GetSysApiRequest): Promise<SysApi>;
  Update(request: UpdateSysApiRequest): Promise<SysApi>;
  Delete(request: DeleteSysApiRequest): Promise<Empty>;
  List(request: ListSysApiRequest): Promise<ListSysApiResponse>;
  BatchCreate(request: BatchCreateSysApisRequest): Promise<BatchCreateSysApisResponse>;
}
