// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               unknown
// source: admin/v1/i_user.proto

/* eslint-disable */
import {
  type CreateUserRequest,
  type DeleteUserRequest,
  type GetUserRequest,
  type ListUserRequest,
  type ListUserResponse,
  type UpdateUserRequest,
  type User,
} from "../../entpb/entpb.pb";
import { type Empty } from "../../google/protobuf/empty.pb";

/** 用户管理服务 */
export interface UserService {
  /** 获取用户列表 */
  List(request: ListUserRequest): Promise<ListUserResponse>;
  /** 获取用户数据 */
  Get(request: GetUserRequest): Promise<User>;
  /** 创建用户 */
  Create(request: CreateUserRequest): Promise<User>;
  /** 更新用户 */
  Update(request: UpdateUserRequest): Promise<User>;
  /** 删除用户 */
  Delete(request: DeleteUserRequest): Promise<Empty>;
}
