// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               unknown
// source: admin/v1/i_village.proto

/* eslint-disable */
import {
  type BatchCreateVillagesRequest,
  type BatchCreateVillagesResponse,
  type CreateVillageRequest,
  type DeleteVillageRequest,
  type GetVillageRequest,
  type ListVillageRequest,
  type ListVillageResponse,
  type UpdateVillageRequest,
  type Village,
} from "../../entpb/entpb.pb";
import { type Empty } from "../../google/protobuf/empty.pb";

export interface VillageService {
  Create(request: CreateVillageRequest): Promise<Village>;
  Get(request: GetVillageRequest): Promise<Village>;
  Update(request: UpdateVillageRequest): Promise<Village>;
  Delete(request: DeleteVillageRequest): Promise<Empty>;
  List(request: ListVillageRequest): Promise<ListVillageResponse>;
  BatchCreate(request: BatchCreateVillagesRequest): Promise<BatchCreateVillagesResponse>;
}
