// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               unknown
// source: admin/v1/i_village.proto

/* eslint-disable */
import { type ListVillageRequest, type ListVillageResponse } from "../../entpb/entpb.pb";

export interface VillageService {
  List(request: ListVillageRequest): Promise<ListVillageResponse>;
}
